# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'woopSicredi-jobs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for woopSicredi-jobs

pod 'Alamofire'
pod 'SteviaLayout'
pod 'AlamofireImage'
pod 'MaterialComponents'

end
